version: "3"
services:
  gitea:
    image: gitea/gitea:1.9.3
    ports:
      - "80:3000"
      - "522:22"
    volumes:
      - ./gitea:/data
    environment:
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - default

  drone-server:
    image: drone/drone:1.3.1
    ports:
      - "8000:80"
      - 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./drone/:/var/lib/drone
    restart: always
    networks:
      - default
    environment:
      - DRONE_OPEN=true
      - DRONE_SERVER_PROTO=http
      - DRONE_SERVER_HOST=drone-server
      # GITEA CONFIG
      - DRONE_GITEA_SERVER=http://gitea:3000
      - TZ=Asia/Shanghai

  drone-agent:
    image: drone/agent:1.3.1
    container_name: drone-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=secret
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - default

networks:
  default:
