version: "3"
services:
  gitea:
    image: gitea/gitea:1
    container_name: gitea
    ports:
      - "3000:3000"
      - "3022:22"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - default

networks:
  default:
